author: Jose Maria Zambrana Arze <contact@josezambrana.com>

exclude_auth: ['contact_form']

default_auth:
  administrator: '*'
  authenticated: ['contact_form']
  anonymous: ['contact_form']

areas:
  Contact Form:
    area: contact,
    name: Contact Form
    description: Manage contact form
    link: contact_admin
    sublinks: {}