author: Jose Maria Zambrana Arze <contact@josezambrana.com>

exclude_auth: ['users_login',
               'users_logout',
               'users_register',
               'users_roles']
default_auth:
  administrator: '*'
  authenticated: ['users_profile',
                  'users_profile_username',
                  'users_settings',
                  'users_logout']
  anonymous: ['users_profile_username', 'users_login', 'users_register']

areas:
  Users:
    area: users
    name: Users
    description: "Manage users, roles and permissions"
    link: users_admin
    sublinks: {"Permissions":"permissions","Roles":"roles",}